# Generated by Django 4.2.29 on 2026-07-05 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('system_role', models.CharField(choices=[('COMPANY_ADMIN', 'Company Admin'), ('STAFF', 'Staff')], max_length=20)),
                ('job_role', models.CharField(blank=True, choices=[('FRONTEND_DEVELOPER', 'Frontend Developer'), ('BACKEND_DEVELOPER', 'Backend Developer'), ('API_DEVELOPER', 'API Developer'), ('UI_UX_DESIGNER', 'UI/UX Designer'), ('TESTER', 'Tester'), ('PROJECT_MANAGER', 'Project Manager')], max_length=30)),
                ('must_change_password', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to='companies.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
